import { Product, CategoryItem, CollectionItem, Coupon, Offer, Order, SiteSettings, AdminUser } from '../types/ecommerce';

export const initialAdmin: AdminUser & { passwordHash: string } = {
  id: 'admin_miljar_01',
  username: process.env.ADMIN_USERNAME || 'Miljar',
  email: 'miljar@richpeople.fashion',
  role: 'super_admin',
  createdAt: '2026-01-01T00:00:00Z',
  // In a lightweight setup we store bcrypt or salt-hash; for seamless portability we store secure hash
  passwordHash: 'Miljar12', // default initial password, can be changed via admin dashboard
};

export const initialSiteSettings: SiteSettings = {
  brandName: 'Rich People',
  tagline: 'Premium quality at a fair price.',
  logo: '/rich-people-logo.svg',
  favicon: '/favicon.ico',
  phone: '+880 1712-345678',
  email: 'concierge@richpeople.fashion',
  address: 'Level 4, House 18, Road 11, Banani, Dhaka-1213, Bangladesh',
  facebook: 'https://facebook.com/richpeople.bd',
  instagram: 'https://instagram.com/richpeople.bd',
  tiktok: 'https://tiktok.com/@richpeople.fashion',
  announcementBar: {
    text: 'FREE SHIPPING ON ALL ORDERS OVER ৳5000 ACROSS BANGLADESH',
    enabled: true,
  },
  freeShippingThreshold: 5000,
  shippingChargeInsideDhaka: 80,
  shippingChargeOutsideDhaka: 150,
  advancePaymentAmount: 200,
  bkashNumber: '01712-345678',
  nagadNumber: '01812-345678',
  paymentInstructions: 'Send ৳200 via "Send Money" (Personal) to confirm order booking. Use your order ID in reference.',
  footerText: '© 2026 Rich People Menswear Atelier. Handcrafted in Bangladesh. All rights reserved.',
  heroSection: {
    title: 'RICH PEOPLE',
    subtitle: 'The 2026 Sartorial Panjabi & Shirt Collection',
    tagline: 'Premium quality at a fair price.',
    ctaTextPrimary: 'Shop Shirts',
    ctaLinkPrimary: '/shop?category=Shirts',
    ctaTextSecondary: 'Shop Panjabi',
    ctaLinkSecondary: '/shop?category=Panjabi',
    image: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
  },
};

export const initialCategories: CategoryItem[] = [
  {
    id: 'cat_rich_people',
    name: 'Rich People Exclusives',
    slug: 'rich-people-exclusives',
    description: 'Bespoke high-density Mulberry silk and Giza 87 Egyptian cotton masterworks.',
    image: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
    order: 0,
    isActive: true,
  },
  {
    id: 'cat_shirts',
    name: 'Shirts',
    slug: 'shirts',
    description: 'Tailored luxury cotton, linen & micro-weave shirts for modern gentlemen.',
    image: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    order: 1,
    isActive: true,
  },
  {
    id: 'cat_panjabi',
    name: 'Panjabi',
    slug: 'panjabi',
    description: 'Bespoke embroidered, textured, and festive Eid Panjabi ensembles.',
    image: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    order: 2,
    isActive: true,
  },
  {
    id: 'cat_cuban',
    name: 'Cuban Collar Shirts',
    slug: 'cuban-collar-shirts',
    description: 'Relaxed resort drape and breathable silhouettes for warm Dhaka evenings.',
    image: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    order: 3,
    isActive: true,
  },
  {
    id: 'cat_eid',
    name: 'Eid Collection',
    slug: 'eid-collection',
    description: 'Exclusive ceremonial wear crafted with metallic threadwork and fine silk blends.',
    image: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    order: 4,
    isActive: true,
  },
  {
    id: 'cat_new_arrivals',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    description: 'The latest drops for the season, freshly tailored in limited batches.',
    image: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
    order: 5,
    isActive: true,
  },
  {
    id: 'cat_sale',
    name: 'Sale',
    slug: 'sale',
    description: 'Special seasonal privileges on selected wardrobe essentials.',
    image: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    order: 6,
    isActive: true,
  },
];

export const initialCollections: CollectionItem[] = [
  {
    id: 'col_monochrome',
    name: 'Signature Monochrome',
    slug: 'signature-monochrome',
    description: 'Deep obsidian blacks, midnight charcoals, and stark stark whites.',
    image: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    banner: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
    isActive: true,
  },
  {
    id: 'col_royal_heritage',
    name: 'Royal Heritage 2026',
    slug: 'royal-heritage-2026',
    description: 'Intricate Bengali needlework meets contemporary royal cuts.',
    image: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    banner: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    isActive: true,
  },
  {
    id: 'col_executive',
    name: 'Executive Essentials',
    slug: 'executive-essentials',
    description: 'High-thread-count Egyptian cotton shirts engineered for power dressing.',
    image: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    isActive: true,
  },
  {
    id: 'col_eid_festive',
    name: 'Festive Eid Edit',
    slug: 'festive-eid-edit',
    description: 'Celebratory Panjabis with discreet luxury accents and satin-finish plackets.',
    image: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    isActive: true,
  },
];

export const initialProducts: Product[] = [
  // ================= 10+ SHIRTS =================
  {
    id: 'prod_shirt_01',
    name: 'Premium Black Full Sleeve Shirt',
    slug: 'premium-black-full-sleeve-shirt',
    sku: 'HMS-SH-001',
    category: 'Shirts',
    collection: 'Signature Monochrome',
    shortDescription: 'Tailored 100% Egyptian Giza Cotton with natural matte luster and mother-of-pearl buttons.',
    description: 'The definitive black shirt. Cut from high-density, double-twisted 120s Egyptian cotton, this shirt offers an impeccably structured drape that resists creasing throughout the day. Finished with German interlining collars and natural mother-of-pearl buttons.',
    price: 1850,
    compareAtPrice: 2250,
    discount: 18,
    costPrice: 950,
    stockQuantity: 42,
    lowStockThreshold: 10,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Deep Obsidian Black'],
    fabric: '100% Giza Compact Cotton (120/2 Count)',
    fit: 'Contemporary Slim Fit',
    weight: '165 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
      '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Shirt', 'Full Sleeve', 'Black', 'Formal', 'Best Seller'],
    seoTitle: 'Premium Black Full Sleeve Shirt | Rich People Luxury Menswear',
    seoDescription: 'Shop our signature 100% Egyptian cotton black full sleeve shirt. Handcrafted in Dhaka with premium mother-of-pearl buttons.',
    status: 'published',
    isFeatured: true,
    isBestSeller: true,
    isSale: true,
    rating: 4.9,
    reviewCount: 38,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'prod_shirt_02',
    name: 'Pure Black All Over Thread Work Shirt',
    slug: 'pure-black-all-over-thread-work-shirt',
    sku: 'HMS-SH-002',
    category: 'Shirts',
    collection: 'Signature Monochrome',
    shortDescription: 'Subtle tone-on-tone embroidered geometric texture for understated evening elegance.',
    description: 'An architectural take on evening shirting. Features tonal matte black embroidery rendered across the front chest and yoke. Light-catching yet whisper-quiet, perfect for high-profile gatherings.',
    price: 2150,
    compareAtPrice: 2600,
    discount: 17,
    costPrice: 1100,
    stockQuantity: 28,
    lowStockThreshold: 8,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Jet Black'],
    fabric: 'Jacquard Dobby Weave Cotton',
    fit: 'Tailored Regular Fit',
    weight: '175 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'Thread Work', 'Embroidery', 'Party Wear'],
    status: 'published',
    isFeatured: true,
    isNewArrival: true,
    isSale: true,
    rating: 4.8,
    reviewCount: 19,
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'prod_shirt_03',
    name: 'Deep Navy Blue Full Sleeve Shirt',
    slug: 'deep-navy-blue-full-sleeve-shirt',
    sku: 'HMS-SH-003',
    category: 'Shirts',
    collection: 'Executive Essentials',
    shortDescription: 'Crisp midnight navy tailored dress shirt with subtle twill texture and spread collar.',
    description: 'Engineered for executive sophistication. The deep midnight dye resists washing fade, while the high-twist micro-twill fabric breathes effortlessly in tropical climates.',
    price: 1750,
    compareAtPrice: 2100,
    discount: 16,
    costPrice: 900,
    stockQuantity: 35,
    lowStockThreshold: 10,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight Navy'],
    fabric: '100% Fine Twill Cotton',
    fit: 'Modern Slim Fit',
    weight: '160 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'Navy', 'Full Sleeve', 'Office'],
    status: 'published',
    isFeatured: false,
    isBestSeller: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 24,
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'prod_shirt_04',
    name: 'White Contrast Full Sleeve Shirt',
    slug: 'white-contrast-full-sleeve-shirt',
    sku: 'HMS-SH-004',
    category: 'Shirts',
    collection: 'Signature Monochrome',
    shortDescription: 'Pristine optic white shirt with charcoal contrast placket piping and engraved cuff details.',
    description: 'A crisp modern staple with bespoke flair. Made from fine poplin cotton with charcoal edge piping inside the placket and inner collar band. A distinctive contrast when worn unbuttoned.',
    price: 1890,
    compareAtPrice: 2300,
    discount: 17,
    costPrice: 950,
    stockQuantity: 19,
    lowStockThreshold: 6,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Optic White / Charcoal Accent'],
    fabric: '100% Supima Cotton Poplin',
    fit: 'Tailored Fit',
    weight: '155 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'White', 'Contrast', 'Formal'],
    status: 'published',
    isFeatured: true,
    isNewArrival: false,
    isSale: false,
    rating: 5.0,
    reviewCount: 31,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod_shirt_05',
    name: 'Light Olive Premium Embroidered Shirt',
    slug: 'light-olive-premium-embroidered-shirt',
    sku: 'HMS-SH-005',
    category: 'Shirts',
    collection: 'Executive Essentials',
    shortDescription: 'Refined sage olive shirt with discreet tonal sleeve embroidery and semi-cutaway collar.',
    description: 'An earthy yet commanding hue. Handcrafted in combed compact yarn with micro embroidery detail along the inner cuff and left chest pocket flap.',
    price: 1990,
    compareAtPrice: 2450,
    discount: 18,
    costPrice: 1000,
    stockQuantity: 22,
    lowStockThreshold: 5,
    sizes: ['M', 'L', 'XL'],
    colors: ['Sage Olive'],
    fabric: 'Soft Peach-Finished Cotton',
    fit: 'Slim Fit',
    weight: '165 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'Olive', 'Embroidered', 'Semi-Formal'],
    status: 'published',
    isFeatured: false,
    isNewArrival: true,
    isSale: true,
    rating: 4.7,
    reviewCount: 12,
    createdAt: '2026-01-24T12:00:00Z',
    updatedAt: '2026-01-24T12:00:00Z',
  },
  {
    id: 'prod_shirt_06',
    name: 'Half Sleeve Cuban Collar Shirt',
    slug: 'half-sleeve-cuban-collar-shirt',
    sku: 'HMS-SH-006',
    category: 'Cuban Collar Shirts',
    collection: 'Modern Cuban Minimalist',
    shortDescription: 'Relaxed retro resort collar in breathable slub rayon-cotton blend for summer ease.',
    description: 'The pinnacle of relaxed luxury. Designed with a wide open camp collar, side slit hem, and natural shell buttons. Ideal for tropical evenings, beach resorts, or stylish casual gatherings.',
    price: 1550,
    compareAtPrice: 1950,
    discount: 20,
    costPrice: 780,
    stockQuantity: 50,
    lowStockThreshold: 12,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal Slate', 'Bone Cream'],
    fabric: 'Slub Cotton-Linen Blend',
    fit: 'Relaxed Resort Fit',
    weight: '145 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'Cuban Collar', 'Half Sleeve', 'Summer', 'Casual'],
    status: 'published',
    isFeatured: true,
    isBestSeller: true,
    isSale: true,
    rating: 4.9,
    reviewCount: 45,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod_shirt_07',
    name: 'Premium Micro Check Full Sleeve Shirt',
    slug: 'premium-micro-check-full-sleeve-shirt',
    sku: 'HMS-SH-007',
    category: 'Shirts',
    collection: 'Executive Essentials',
    shortDescription: 'Subtle micro houndstooth check in wine burgundy and charcoal black threads.',
    description: 'Rich in detail up close, clean and solid from afar. Woven with dyed yarns that deliver remarkable depth and color richness.',
    price: 1850,
    compareAtPrice: 2200,
    discount: 15,
    costPrice: 920,
    stockQuantity: 31,
    lowStockThreshold: 8,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Burgundy Micro Check'],
    fabric: '100% Yarn Dyed Cotton',
    fit: 'Contemporary Fit',
    weight: '160 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Shirt', 'Check', 'Burgundy', 'Smart Casual'],
    status: 'published',
    isFeatured: false,
    isNewArrival: false,
    isSale: false,
    rating: 4.8,
    reviewCount: 16,
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'prod_shirt_08',
    name: 'Flannel Jacquard High GSM Winter Check Shirt',
    slug: 'flannel-jacquard-high-gsm-winter-check-shirt',
    sku: 'HMS-SH-008',
    category: 'Shirts',
    collection: 'Signature Monochrome',
    shortDescription: 'Heavyweight brushed 220 GSM flannel shirt with double chest patch pockets.',
    description: 'Constructed from heavy 220 GSM brushed winter cotton. Warm, extraordinarily soft to the hand, and cut slightly roomier to allow layering over tees.',
    price: 2250,
    compareAtPrice: 2800,
    discount: 19,
    costPrice: 1150,
    stockQuantity: 15,
    lowStockThreshold: 5,
    sizes: ['M', 'L', 'XL'],
    colors: ['Charcoal & Wine Tartan'],
    fabric: '100% Brushed Flannel Jacquard',
    fit: 'Over-shirt Fit',
    weight: '220 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Shirt', 'Flannel', 'Winter', 'Overshirt'],
    status: 'published',
    isFeatured: false,
    isNewArrival: true,
    isSale: true,
    rating: 4.9,
    reviewCount: 21,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'prod_shirt_09',
    name: 'Embroidery Work Full Sleeve Shirt',
    slug: 'embroidery-work-full-sleeve-shirt',
    sku: 'HMS-SH-009',
    category: 'Shirts',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Fine hand-finished chest embroidery with antique metallic buttons and mandarin collar.',
    description: 'A crossover between bespoke shirt craftsmanship and regal panjabi styling. Features a standing band collar with exquisite silk thread work across the shoulder yoke.',
    price: 2450,
    compareAtPrice: 2950,
    discount: 16,
    costPrice: 1250,
    stockQuantity: 18,
    lowStockThreshold: 5,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight Black'],
    fabric: 'Silk-Cotton Luster Blend',
    fit: 'Tailored Royal Fit',
    weight: '170 GSM',
    featuredImage: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
    images: [
      '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg'
    ],
    tags: ['Shirt', 'Embroidery', 'Band Collar', 'Festive'],
    status: 'published',
    isFeatured: true,
    isNewArrival: true,
    isSale: false,
    rating: 5.0,
    reviewCount: 27,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'prod_shirt_10',
    name: 'Bespoke Wine Burgundy Formal Shirt',
    slug: 'bespoke-wine-burgundy-formal-shirt',
    sku: 'HMS-SH-010',
    category: 'Shirts',
    collection: 'Signature Monochrome',
    shortDescription: 'Rich wine red twill shirt designed to pair effortlessly with dark charcoal blazers.',
    description: 'Imbued with a rich deep wine hue that exudes luxury under evening lights. Mercerized finish gives an elevated satin sheen without being ostentatious.',
    price: 1950,
    compareAtPrice: 2400,
    discount: 18,
    costPrice: 980,
    stockQuantity: 27,
    lowStockThreshold: 7,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Wine Burgundy'],
    fabric: '100% Mercerized Cotton Twill',
    fit: 'Slim Fit',
    weight: '160 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Shirt', 'Burgundy', 'Wine', 'Formal'],
    status: 'published',
    isFeatured: false,
    isBestSeller: true,
    isSale: true,
    rating: 4.8,
    reviewCount: 15,
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
  },

  // ================= 10+ PANJABI =================
  {
    id: 'prod_panjabi_01',
    name: 'Premium Black Panjabi',
    slug: 'premium-black-panjabi',
    sku: 'HMS-PJ-001',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Ultra-refined jet black silk-cotton blend Panjabi with minimalist collar piping.',
    description: 'Our quintessential black Panjabi. Engineered for modern kings, with a subtle natural luster, high collar stand, matte metal snap buttons, and deep welt pockets on both sides.',
    price: 2850,
    compareAtPrice: 3500,
    discount: 18,
    costPrice: 1400,
    stockQuantity: 36,
    lowStockThreshold: 10,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Deep Jet Black'],
    fabric: '70% Long-Staple Cotton, 30% Mulberry Silk',
    fit: 'Semi-Fitted Tailored Cut',
    weight: '180 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
      '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Panjabi', 'Black', 'Best Seller', 'Luxury', 'Eid'],
    seoTitle: 'Premium Black Panjabi | Rich People Luxury Bangladesh Menswear',
    seoDescription: 'Handcrafted premium black Panjabi in silk-cotton blend. Perfect for Eid and celebrations.',
    status: 'published',
    isFeatured: true,
    isBestSeller: true,
    isSale: true,
    rating: 5.0,
    reviewCount: 52,
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-01-05T10:00:00Z',
  },
  {
    id: 'prod_panjabi_02',
    name: 'Classic White Panjabi',
    slug: 'classic-white-panjabi',
    sku: 'HMS-PJ-002',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Pure pearl white linen-cotton Panjabi with tone-on-tone neckline embroidery.',
    description: 'Timeless serenity. Cut from high-twist combed cotton and breathable flax linen. The neckline features delicate geometric cordon embroidery that remains elegant and refined.',
    price: 2650,
    compareAtPrice: 3200,
    discount: 17,
    costPrice: 1300,
    stockQuantity: 40,
    lowStockThreshold: 8,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Pristine Pearl White'],
    fabric: '80% Combed Cotton, 20% European Linen',
    fit: 'Standard Semi-Fitted',
    weight: '175 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'White', 'Classic', 'Jumma', 'Eid'],
    status: 'published',
    isFeatured: true,
    isBestSeller: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 41,
    createdAt: '2026-01-08T10:00:00Z',
    updatedAt: '2026-01-08T10:00:00Z',
  },
  {
    id: 'prod_panjabi_03',
    name: 'Premium Olive Panjabi',
    slug: 'premium-olive-panjabi',
    sku: 'HMS-PJ-003',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Earthy military olive with antique brass button closure and clean textured weave.',
    description: 'A distinctive contemporary hue for discerning tastes. Features a textured slub finish with double-stitch hem reinforcement and handcrafted brass cuff buttons.',
    price: 2750,
    compareAtPrice: 3350,
    discount: 17,
    costPrice: 1350,
    stockQuantity: 24,
    lowStockThreshold: 6,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Deep Olive Green'],
    fabric: '100% Slub Textured Cotton',
    fit: 'Tailored Slim Cut',
    weight: '185 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Olive', 'Textured', 'Modern'],
    status: 'published',
    isFeatured: false,
    isNewArrival: true,
    isSale: true,
    rating: 4.8,
    reviewCount: 18,
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'prod_panjabi_04',
    name: 'Embroidered Panjabi',
    slug: 'embroidered-panjabi',
    sku: 'HMS-PJ-004',
    category: 'Panjabi',
    collection: 'Festive Eid Edit',
    shortDescription: 'Intricate zari threadwork across collar and placket on a deep charcoal ground.',
    description: 'Masterful embroidery inspired by historic Bengal court attire. Fine metallic threads are intertwined with charcoal silk fibers to create an opulent neckline.',
    price: 3450,
    compareAtPrice: 4200,
    discount: 17,
    costPrice: 1700,
    stockQuantity: 20,
    lowStockThreshold: 5,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Obsidian Black / Antique Zari'],
    fabric: 'Fine Jacquard Silk-Cotton Weave',
    fit: 'Royal Tailored Cut',
    weight: '190 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Embroidered', 'Zari', 'Wedding', 'Festive'],
    status: 'published',
    isFeatured: true,
    isNewArrival: true,
    isSale: false,
    rating: 5.0,
    reviewCount: 33,
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: 'prod_panjabi_05',
    name: 'Eid Premium Panjabi',
    slug: 'eid-premium-panjabi',
    sku: 'HMS-PJ-005',
    category: 'Eid Collection',
    collection: 'Festive Eid Edit',
    shortDescription: 'Our flagship Eid release featuring bespoke cutwork placket and burgundy silk lining.',
    description: 'The pinnacle of our Festive 2026 offering. Hand-loomed with high-twist yarns, featuring hand-carved horn buttons and discreet burgundy silk accents hidden within the side vents.',
    price: 3850,
    compareAtPrice: 4800,
    discount: 19,
    costPrice: 1900,
    stockQuantity: 15,
    lowStockThreshold: 4,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Midnight Wine & Black'],
    fabric: 'Bespoke Tussar Cotton Silk Blend',
    fit: 'Regal Contemporary Fit',
    weight: '195 GSM',
    featuredImage: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
    images: [
      '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Panjabi', 'Eid', 'Premium', 'Exclusive', 'Silk'],
    status: 'published',
    isFeatured: true,
    isNewArrival: true,
    isSale: true,
    rating: 5.0,
    reviewCount: 47,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'prod_panjabi_06',
    name: 'Cotton Panjabi',
    slug: 'cotton-panjabi',
    sku: 'HMS-PJ-006',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Breathable 100% organic cotton everyday Panjabi with minimalist collar stitch.',
    description: 'Designed for daily devotion and effortless elegance. Ultra-light, highly absorbent, and softens with every wash without losing its crisp drape.',
    price: 2150,
    compareAtPrice: 2600,
    discount: 17,
    costPrice: 1050,
    stockQuantity: 45,
    lowStockThreshold: 10,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Slate Grey', 'Off-White'],
    fabric: '100% Combed Organic Cotton',
    fit: 'Relaxed Regular Fit',
    weight: '155 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Cotton', 'Casual', 'Everyday'],
    status: 'published',
    isFeatured: false,
    isBestSeller: true,
    isSale: false,
    rating: 4.8,
    reviewCount: 29,
    createdAt: '2026-02-04T10:00:00Z',
    updatedAt: '2026-02-04T10:00:00Z',
  },
  {
    id: 'prod_panjabi_07',
    name: 'Linen Panjabi',
    slug: 'linen-panjabi',
    sku: 'HMS-PJ-007',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: '100% Pure Normandy Linen Panjabi with airy open weave and mother-of-pearl buttons.',
    description: 'The supreme hot-weather fabric. Natural flax linen fibers promote continuous air circulation, imparting a relaxed architectural crinkle that looks effortlessly wealthy.',
    price: 3250,
    compareAtPrice: 3950,
    discount: 17,
    costPrice: 1600,
    stockQuantity: 18,
    lowStockThreshold: 5,
    sizes: ['M', 'L', 'XL'],
    colors: ['Natural Flax Beige', 'Charcoal'],
    fabric: '100% European Flax Linen',
    fit: 'Airy Comfort Cut',
    weight: '165 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Linen', 'Summer', 'Luxury'],
    status: 'published',
    isFeatured: true,
    isNewArrival: false,
    isSale: true,
    rating: 4.9,
    reviewCount: 22,
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'prod_panjabi_08',
    name: 'Premium Textured Panjabi',
    slug: 'premium-textured-panjabi',
    sku: 'HMS-PJ-008',
    category: 'Panjabi',
    collection: 'Royal Heritage 2026',
    shortDescription: 'Woven micro-diamond texture in deep maroon burgundy with concealed front placket.',
    description: 'Rich dimensionality and understated power. The concealed button placket gives a razor-clean front profile while the micro-diamond weave plays subtly with shadows.',
    price: 2950,
    compareAtPrice: 3600,
    discount: 18,
    costPrice: 1450,
    stockQuantity: 26,
    lowStockThreshold: 7,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Deep Maroon Burgundy'],
    fabric: 'Dobby Weave Luster Cotton',
    fit: 'Tailored Slim Fit',
    weight: '185 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Textured', 'Maroon', 'Burgundy', 'Party'],
    status: 'published',
    isFeatured: false,
    isBestSeller: true,
    isSale: true,
    rating: 4.9,
    reviewCount: 35,
    createdAt: '2026-02-12T10:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    id: 'prod_panjabi_09',
    name: 'Royal Navy Embroidered Panjabi',
    slug: 'royal-navy-embroidered-panjabi',
    sku: 'HMS-PJ-009',
    category: 'Panjabi',
    collection: 'Festive Eid Edit',
    shortDescription: 'Deep royal navy blue with silver-grey silk thread neck embroidery and concealed snaps.',
    description: 'An aristocratic color palette. Hand-finished collar detailing with matching embroidery cuffs. Pair with raw off-white silk churidar or tailored trousers.',
    price: 3350,
    compareAtPrice: 4100,
    discount: 18,
    costPrice: 1650,
    stockQuantity: 21,
    lowStockThreshold: 6,
    sizes: ['M', 'L', 'XL'],
    colors: ['Royal Navy'],
    fabric: 'Jacquard Silk-Cotton Twill',
    fit: 'Tailored Fit',
    weight: '180 GSM',
    featuredImage: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
    images: [
      '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg'
    ],
    tags: ['Panjabi', 'Navy', 'Embroidered', 'Festive'],
    status: 'published',
    isFeatured: false,
    isNewArrival: true,
    isSale: false,
    rating: 4.8,
    reviewCount: 17,
    createdAt: '2026-02-16T10:00:00Z',
    updatedAt: '2026-02-16T10:00:00Z',
  },
  {
    id: 'prod_panjabi_10',
    name: 'Signature Emerald Green Silk Panjabi',
    slug: 'signature-emerald-green-silk-panjabi',
    sku: 'HMS-PJ-010',
    category: 'Eid Collection',
    collection: 'Festive Eid Edit',
    shortDescription: 'Jewel-tone deep emerald green with brushed gold buttons and mandarin collar.',
    description: 'A striking festive statement. The deep emerald hue catches ambient light with a silky sheen. Finished with bespoke cast brass buttons with the Rich People crest imprint.',
    price: 3650,
    compareAtPrice: 4500,
    discount: 18,
    costPrice: 1800,
    stockQuantity: 14,
    lowStockThreshold: 4,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Deep Emerald Green'],
    fabric: '65% Combed Cotton, 35% Silk Weave',
    fit: 'Tailored Slim Cut',
    weight: '185 GSM',
    featuredImage: '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg',
    images: [
      '/src/assets/images/craftsmanship_fabric_banner_1791384259700.jpg'
    ],
    tags: ['Panjabi', 'Green', 'Silk', 'Festive', 'Limited Run'],
    status: 'published',
    isFeatured: true,
    isNewArrival: true,
    isSale: true,
    rating: 5.0,
    reviewCount: 26,
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'cpn_welcome10',
    code: 'WELCOME10',
    discountType: 'percentage',
    discountAmount: 10,
    minOrderAmount: 1500,
    maxDiscountAmount: 500,
    usageLimit: 1000,
    usedCount: 84,
    perUserLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_eid20',
    code: 'EID20',
    discountType: 'percentage',
    discountAmount: 20,
    minOrderAmount: 4000,
    maxDiscountAmount: 1200,
    usageLimit: 500,
    usedCount: 162,
    perUserLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_rich_people',
    code: 'RICHPEOPLE',
    discountType: 'percentage',
    discountAmount: 15,
    minOrderAmount: 3000,
    maxDiscountAmount: 1500,
    usageLimit: 1000,
    usedCount: 88,
    perUserLimit: 2,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_rich500',
    code: 'RICH500',
    discountType: 'fixed',
    discountAmount: 500,
    minOrderAmount: 3000,
    usageLimit: 500,
    usedCount: 72,
    perUserLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_heems500',
    code: 'HEEMS500',
    discountType: 'fixed',
    discountAmount: 500,
    minOrderAmount: 3000,
    usageLimit: 250,
    usedCount: 47,
    perUserLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_freeship',
    code: 'FREESHIP',
    discountType: 'fixed',
    discountAmount: 150,
    minOrderAmount: 2000,
    usageLimit: 1000,
    usedCount: 210,
    perUserLimit: 2,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn_vip15',
    code: 'VIP15',
    discountType: 'percentage',
    discountAmount: 15,
    minOrderAmount: 2500,
    maxDiscountAmount: 800,
    usageLimit: 300,
    usedCount: 39,
    perUserLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
];

export const initialOffers: Offer[] = [
  {
    id: 'off_eid_special',
    name: 'Eid Ul Fitr Exclusive - Up to 25% Off',
    offerType: 'percentage',
    discountAmount: 20,
    applicableCategories: ['Panjabi', 'Eid Collection'],
    minOrderAmount: 3000,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'off_duo_pack',
    name: 'Executive Shirt Bundle Privileges',
    offerType: 'fixed',
    discountAmount: 400,
    applicableCategories: ['Shirts'],
    minOrderAmount: 3500,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'off_panjabi_festive',
    name: 'Heritage Panjabi Grand Privilege',
    offerType: 'percentage',
    discountAmount: 15,
    applicableCategories: ['Panjabi'],
    minOrderAmount: 2500,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'RICH-2026-00001',
    customerName: 'Tanvir Ahmed',
    customerPhone: '01711223344',
    customerEmail: 'tanvir.ahmed@gmail.com',
    shippingAddress: {
      customerName: 'Tanvir Ahmed',
      phone: '01711223344',
      email: 'tanvir.ahmed@gmail.com',
      division: 'Dhaka',
      district: 'Dhaka',
      area: 'Banani',
      fullAddress: 'Flat 4A, Road 11, Block D, Banani',
      postCode: '1213',
      notes: 'Call before delivery please',
    },
    deliveryMethod: 'Inside Dhaka',
    items: [
      {
        productId: 'prod_shirt_01',
        name: 'Premium Black Full Sleeve Shirt',
        slug: 'premium-black-full-sleeve-shirt',
        image: '/src/assets/images/luxury_shirt_showcase_1791384245775.jpg',
        size: 'L',
        color: 'Deep Obsidian Black',
        price: 1850,
        quantity: 1,
        total: 1850,
      },
    ],
    subtotal: 1850,
    shippingCharge: 80,
    discountAmount: 0,
    grandTotal: 1930,
    advancePaid: 200,
    remainingCOD: 1730,
    paymentMethod: 'bKash',
    transactionId: '9K28M9X41P',
    senderPhone: '01711223344',
    paymentStatus: 'PAID',
    orderStatus: 'CONFIRMED',
    statusHistory: [
      { status: 'PAYMENT_UNDER_REVIEW', timestamp: '2026-03-01T14:20:00Z', note: 'Order placed with bKash advance TrxID 9K28M9X41P' },
      { status: 'CONFIRMED', timestamp: '2026-03-01T15:10:00Z', note: 'bKash payment verified by admin Miljar' },
    ],
    adminNotes: ['bKash statement verified on 01712-345678'],
    createdAt: '2026-03-01T14:20:00Z',
    updatedAt: '2026-03-01T15:10:00Z',
  },
  {
    id: 'RICH-2026-00002',
    customerName: 'Rashidul Islam',
    customerPhone: '01819556677',
    customerEmail: 'rashid.chy@yahoo.com',
    shippingAddress: {
      customerName: 'Rashidul Islam',
      phone: '01819556677',
      email: 'rashid.chy@yahoo.com',
      division: 'Chittagong',
      district: 'Chittagong',
      area: 'Nasirabad',
      fullAddress: 'House 14, Road 2, O.R Nizam Road, Nasirabad',
      postCode: '4000',
    },
    deliveryMethod: 'Outside Dhaka',
    items: [
      {
        productId: 'prod_panjabi_01',
        name: 'Premium Black Panjabi',
        slug: 'premium-black-panjabi',
        image: '/src/assets/images/luxury_panjabi_showcase_1791384227946.jpg',
        size: 'XL',
        color: 'Deep Jet Black',
        price: 2850,
        quantity: 1,
        total: 2850,
      },
    ],
    subtotal: 2850,
    shippingCharge: 150,
    discountAmount: 200,
    couponCode: 'WELCOME10',
    grandTotal: 2800,
    advancePaid: 200,
    remainingCOD: 2600,
    paymentMethod: 'Nagad',
    transactionId: 'NAG7719283X',
    senderPhone: '01819556677',
    paymentStatus: 'PAID',
    orderStatus: 'SHIPPED',
    statusHistory: [
      { status: 'PAYMENT_UNDER_REVIEW', timestamp: '2026-03-02T10:15:00Z' },
      { status: 'CONFIRMED', timestamp: '2026-03-02T11:00:00Z' },
      { status: 'PROCESSING', timestamp: '2026-03-02T13:00:00Z' },
      { status: 'SHIPPED', timestamp: '2026-03-03T09:30:00Z', note: 'Dispatched via Steadfast Courier #SF-991204' },
    ],
    adminNotes: ['Steadfast Tracking: SF-991204'],
    createdAt: '2026-03-02T10:15:00Z',
    updatedAt: '2026-03-03T09:30:00Z',
  },
  {
    id: 'RICH-2026-00003',
    customerName: 'Shamsul Arefin',
    customerPhone: '01911998877',
    customerEmail: 'arefin.shams@outlook.com',
    shippingAddress: {
      customerName: 'Shamsul Arefin',
      phone: '01911998877',
      email: 'arefin.shams@outlook.com',
      division: 'Dhaka',
      district: 'Dhaka',
      area: 'Dhanmondi',
      fullAddress: 'House 27/A, Road 8, Dhanmondi',
      postCode: '1205',
    },
    deliveryMethod: 'Inside Dhaka',
    items: [
      {
        productId: 'prod_panjabi_05',
        name: 'Eid Premium Panjabi',
        slug: 'eid-premium-panjabi',
        image: '/src/assets/images/hero_luxury_menswear_1791384214280.jpg',
        size: 'L',
        color: 'Midnight Wine & Black',
        price: 3850,
        quantity: 1,
        total: 3850,
      },
    ],
    subtotal: 3850,
    shippingCharge: 80,
    discountAmount: 0,
    grandTotal: 3930,
    advancePaid: 200,
    remainingCOD: 3730,
    paymentMethod: 'bKash',
    transactionId: 'BK9012351AA',
    senderPhone: '01911998877',
    paymentStatus: 'PENDING_VERIFICATION',
    orderStatus: 'PAYMENT_UNDER_REVIEW',
    statusHistory: [
      { status: 'PAYMENT_UNDER_REVIEW', timestamp: '2026-03-04T16:45:00Z', note: 'Customer submitted bKash transaction BK9012351AA' },
    ],
    adminNotes: ['Awaiting statement check'],
    createdAt: '2026-03-04T16:45:00Z',
    updatedAt: '2026-03-04T16:45:00Z',
  },
];
